version: "2" # https://golangci-lint.run/usage/configuration/
linters:
  default: fast
  enable:
    - wsl_v5
  disable:
    - wsl
    - depguard
    - copyloopvar
    - cyclop        # Complex functions are acceptable for storage operations
    - funcorder     # Method ordering is less important than code locality
    - interfacebloat # Storage interface intentionally has many methods
    - nestif        # Some nested conditions are more readable

  # settings:
  #   lll:
  #     line-length: 160

  #   wsl_v5:
  #     allow-first-in-block: true
  #     allow-whole-block: false
  #     branch-max-lines: 2

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
